NUMPY

In [ ]:
import numpy as np


In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
a=np.array([1,2,3,4,5])

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
type(a)

numpy.ndarray

In [9]:
np.array([1.2,1,8,6.4,3],dtype="int")

array([1, 1, 8, 6, 3])

In [10]:
b=np.array([10,20,30,40])
b.ndim

1

In [13]:
c=np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

Tek boyutlu array: vektör, İki boyutlu array: matris

In [14]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
d.ndim

2

In [17]:
#Sıfırlardan oluşan dizi oluşturma:
e=np.zeros((3,4))
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
#Birlerden oluşan dizi oluşturma:
f=np.ones((4,3,4), dtype=np.int16)
f          

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
g=np.arange(0,100,10)
g

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
g.shape

(10,)

In [27]:
#Belirli bir başlangıç ve bitiş aralığında eşit aralıklarla dilimleyerek değerler oluşturma:
h=np.linspace(1,10,5)
h

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [29]:
#Belirli bir sayıdan oluşan array oluşturma:
i = np.full((2,3),7)
i

array([[7, 7, 7],
       [7, 7, 7]])

In [30]:
#köşegen değerleri 1 geri kalan kısmı ise 0'lardan oluşan array:
j = np.eye(3)
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#İçi rastgele değerler içeren bir matris oluşturma:
k=np.random.random((1,3))
k

array([[0.50858535, 0.86205345, 0.83544417]])

In [37]:
#Normal dağılıma uygun veri: (ortalaması 10, ss 4 olan arrayler)
l=np.random.normal(10,4,(3,4))
l

array([[ 5.51093377, 11.01274012, 12.59291458, 10.0469943 ],
       [17.64854856, 10.70444989, 13.22514328, 12.4698527 ],
       [10.25073452,  5.26155795,  7.00314635, 13.70776857]])

In [38]:
#Integer değerlerden rastgele bir şekilde oluşturulmuş bir veri oluşturmak için:
m=np.random.randint(0,10,size=(3,3))
m

array([[8, 2, 8],
       [5, 4, 1],
       [2, 9, 1]])

In [42]:
n=np.random.randint(10,size=10)
n

array([7, 9, 2, 9, 0, 6, 2, 2, 2, 6])

In [43]:
#boyut sayisi
n.ndim

1

In [44]:
#boyut bilgisi
n.shape

(10,)

In [45]:
#Toplam eleman sayısı
n.size

10

In [46]:
#Array veri tipi
n.dtype

dtype('int32')

In [48]:
#İki Boyutlu Array oluşturma:
p=np.random.randint(100,size=(3,5))
p

array([[43, 40, 47, 29, 45],
       [84, 63, 14, 46, 35],
       [99, 83, 81, 37, 11]])

In [49]:
p.ndim

2

In [50]:
p.shape

(3, 5)

In [51]:
p.size

15

In [52]:
n.dtype

dtype('int32')

Yeniden Şekillendirme (reshaping)

In [ ]:
import numpy as np

In [53]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
#Mevcut array üzerinden yeniden bir array (2 boyutlu) oluşturmak:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
a= np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
a.reshape((3,3))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a.ndim

1

array birlestirme

In [66]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [68]:
#Arrayleri birleştirmek için:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

iki boyut uzerinde birlestirme

In [4]:
#Elle liste üzerinden numpy arrayi oluşturma:
a= np.array([[1,2,3], 
            [4,5,6]])

In [5]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
#sütun bazında birleştirmek için: axis eksen belirtmek için kullanılır. 0: satır, 1:sütunu ifade eder.
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [7]:
np.concatenate([a,a],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

array ayirma(splitting)

In [10]:
x=np.array([10,12,34,65,89,32,21,41])

In [11]:
#Arrayi ayırmak için:(3'e kadar bir böl, 5' kadar bir böl, geriye kalanı ayrı böl)-2 değer girince 3 parçaya ayırır.
np.split(x, [3,5])

[array([10, 12, 34]), array([65, 89]), array([32, 21, 41])]

In [12]:
#Böldüğümüz arrayleri ayrı değişkenlerde saklamak için:
a,b,c= np.split(x, [3,5])

In [13]:
a

array([10, 12, 34])

In [14]:
b

array([65, 89])

In [15]:
c

array([32, 21, 41])

iki boyutlu arrayi ayirma

In [17]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
#2 boyutlu arrayi 2. satırdan sonraki satırdan bölmek için:(yatay olarak bölme işlemi:vsplit)
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [20]:
ust, alt= np.vsplit(m, [2])

In [21]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
#2 boyutlu arrayi 2. sütundan sonraki sütundan bölmek için:(dikey olarak bölme işlemi:hsplit)
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [25]:
sag, sol= np.hsplit(m, [2])

In [26]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [27]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

sıralama

In [29]:
v=np.array([20,18,49,33,59])
v

array([20, 18, 49, 33, 59])

In [30]:
np.sort(v)

array([18, 20, 33, 49, 59])

In [31]:
v

array([20, 18, 49, 33, 59])

iki boyutlu array sıralama

In [32]:
#Ortalaması 20, ss=5 olan bir array:
m= np.random.normal(20,5, (3,3))
m

array([[22.74229439, 19.02691189, 19.94332271],
       [14.59807077, 26.47601859, 21.33516769],
       [ 9.49536494, 24.68100648, 19.49546744]])

In [33]:
np.sort(m, axis=1) #satırlara göre sıraladı

array([[19.02691189, 19.94332271, 22.74229439],
       [14.59807077, 21.33516769, 26.47601859],
       [ 9.49536494, 19.49546744, 24.68100648]])

In [34]:
np.sort(m,axis=0) #sutünlara göre sıraladı

array([[ 9.49536494, 19.02691189, 19.49546744],
       [14.59807077, 24.68100648, 19.94332271],
       [22.74229439, 26.47601859, 21.33516769]])

In [35]:
n=np.random.randint(0,10,size=(3,3))
n

array([[8, 4, 3],
       [3, 7, 7],
       [2, 4, 8]])

In [36]:
np.sort(n,axis=1)

array([[3, 4, 8],
       [3, 7, 7],
       [2, 4, 8]])

In [38]:
np.sort(n,axis=0)

array([[2, 4, 3],
       [3, 4, 7],
       [8, 7, 8]])

index ile elemanlara erişmek

In [39]:
a=np.random.randint(10, size=10)
a

array([5, 7, 4, 0, 8, 8, 6, 0, 8, 5])

In [40]:
a[0]

5

In [42]:
a[-2]

8

In [45]:
a[0]=100
a

array([100,   7,   4,   0,   8,   8,   6,   0,   8,   5])

In [46]:
#İki boyutlu bir array oluşturma ve elemanlarına erişme:
m = np.random.randint(10, size=(3,5))
m

array([[5, 6, 2, 8, 9],
       [6, 4, 4, 9, 4],
       [4, 5, 1, 3, 4]])

In [47]:
m[0,0]

5

In [49]:
m[0,0]=22
m

array([[22,  6,  2,  8,  9],
       [ 6,  4,  4,  9,  4],
       [ 4,  5,  1,  3,  4]])

In [53]:
#Numpy arrayleri sabit değişkenlidir. Float eklemeye çalışırsan int olduğu için değişiklik olmaz)
m[1,4]= 2.2
m

array([[22,  6,  2,  8,  9],
       [ 6,  4,  4,  9,  2],
       [ 4,  5,  1,  3,  4]])

slicing ile elemanlara erişmek(array alt kumesine erişmek)

In [54]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [55]:
a[0:3]

array([20, 21, 22])

In [56]:
a[:3]

array([20, 21, 22])

In [57]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [58]:
#1'den başla 2'şer atlayarak sona kadar git
a[1::2]

array([21, 23, 25, 27, 29])

In [59]:
a[0::2]

array([20, 22, 24, 26, 28])

In [61]:
a[0::3]

array([20, 23, 26, 29])

iki boyutlu slice islemleri

In [62]:
m= np.random.randint(10, size=(5,5))
m

array([[9, 5, 8, 2, 6],
       [7, 6, 7, 1, 6],
       [5, 4, 4, 3, 9],
       [1, 3, 0, 2, 6],
       [3, 1, 8, 9, 9]])

In [63]:
#[Bütün satırları seç, ilk sütunu seç]
m[:,0]

array([9, 7, 5, 1, 3])

In [64]:
#[indekse göre 2. satır, Bütün sütunları seç]
m[2,:]

array([5, 4, 4, 3, 9])

In [65]:
m[0]

array([9, 5, 8, 2, 6])

In [68]:
m[1,:]

array([7, 6, 7, 1, 6])

In [69]:
m[:]

array([[9, 5, 8, 2, 6],
       [7, 6, 7, 1, 6],
       [5, 4, 4, 3, 9],
       [1, 3, 0, 2, 6],
       [3, 1, 8, 9, 9]])

In [67]:
#0'dan 2'ye kadar satırları al, 0'dan 3'e kadar sütunları al
m[0:2, 0:3]

array([[9, 5, 8],
       [7, 6, 7]])

In [70]:
m[:,:2]

array([[9, 5],
       [7, 6],
       [5, 4],
       [1, 3],
       [3, 1]])

In [71]:
m[1:3,0:2]

array([[7, 6],
       [5, 4]])

alt kume uzerinde işlem yapmak

In [74]:
a= np.random.randint(100, size=(5,5))
a

array([[ 2,  3, 59, 88, 95],
       [88, 87, 13, 90, 29],
       [61, 61, 48, 94, 70],
       [ 3, 89, 26, 75, 33],
       [90, 36, 39, 85, 78]])

In [75]:
alt_a= a[0:3, 0:2]
alt_a

array([[ 2,  3],
       [88, 87],
       [61, 61]])

In [77]:
alt_a[0,0]= 99999
alt_a[1,1]= 888
alt_a

array([[99999,     3],
       [   88,   888],
       [   61,    61]])

In [78]:
#Alt kümedeki değişiklik asıl veri setine de yansıdı.
a

array([[99999,     3,    59,    88,    95],
       [   88,   888,    13,    90,    29],
       [   61,    61,    48,    94,    70],
       [    3,    89,    26,    75,    33],
       [   90,    36,    39,    85,    78]])

In [79]:
m= np.random.randint(10, size=(5,5))
m

array([[1, 6, 3, 3, 1],
       [3, 6, 1, 3, 9],
       [0, 8, 3, 9, 3],
       [5, 1, 9, 2, 1],
       [4, 2, 4, 5, 3]])

In [80]:
#Ana veriler bozulmasın istiyorsak copy methodunu kullanabiliriz:
alt_b= m[0:3,0:2].copy()
alt_b

array([[1, 6],
       [3, 6],
       [0, 8]])

In [82]:
alt_b[0,0]= 9999
alt_b

array([[9999,    6],
       [   3,    6],
       [   0,    8]])

In [83]:
m

array([[1, 6, 3, 3, 1],
       [3, 6, 1, 3, 9],
       [0, 8, 3, 9, 3],
       [5, 1, 9, 2, 1],
       [4, 2, 4, 5, 3]])

fancyIndex ile elemanlara erişme

In [84]:
#En önemli kavramlardan biridir. Hem Pandas hem Numpy'da ileri düzey eleman seçme imkanı verir.
#Çok sayıda indeks olduğunda tek seferde sorgulama yapmak için Fancyindex kullanılabilir.
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [85]:
#Seçilen elemanları bir arada görmek için:
[v[1], v[3], v[5]]

[3, 9, 15]

In [86]:
indx_no= [1,3,5]

In [88]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [90]:
#Fancyindex: Elimizdeki yüzlerce değer üreten bir fonksiyon vs. varsa ve liste olarak kaydedilirse bu şekilde kullanılır:
v[indx_no]

array([ 3,  9, 15])

iki boyutta fancy

In [91]:
m=np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
#Satırdan ve sütundan seçtiğimiz indeksleri belirtelim:
#0. satır 1. sütun elemanı:
satir= np.array([0,1])
#1. satır 2. sütun elemanı:
sutun=np.array([1,2])

In [97]:
m[satir, sutun]

array([1, 5])

basit index ile fancy index

In [98]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
m[0, [1,2]]

array([1, 2])

In [93]:
#slice,fancy
m[0:2, [1,2]]

array([[1, 2],
       [4, 5]])

koşullu eleman işlemleri

In [99]:
#Belirli bir arrayin içindeki koşulu sağlayan elemanların çağırılması:
v= np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [100]:
v<3

array([ True,  True, False, False, False])

In [101]:
#Şartı sağlayan elemanlara erişmek : (v'nin 3'ten küçük olduğu değerleri getirir.)
v[v<3]

array([1, 2])

In [102]:
v*2

array([ 2,  4,  6,  8, 10])

In [103]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [104]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [105]:
v

array([1, 2, 3, 4, 5])

matematiksel işlemler

In [106]:
v= np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [107]:
# v-1 işlemi (bu tür fonskiyonlar "ufunc" olarak adlandırılır)
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [109]:
np.subtract(v,2)

array([-1,  0,  1,  2,  3])

In [110]:
# v+1 işlemi
np.add(v,1)

array([2, 3, 4, 5, 6])

In [111]:
# v*4 işlemi
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [112]:
# v/3 işlemi
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [113]:
# v**3 işlemi
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [114]:
#v'nin 2'ye bölümünden kalanlar:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [115]:
# v % 2 işlemi
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [116]:
#Mutlak değer işlemi:
np.absolute(np.array([-3]))

array([3])

In [117]:
#Sin değeri hesaplama:
np.sin(360)

0.9589157234143065

In [118]:
np.cos(180)

-0.5984600690578581

In [119]:
#v'nin içindeki elemanların Logunu alma işlemi
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [121]:
np.log2(v)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [122]:
#cheat sheet ile googledan ekstra bilgi alabiliriz

PANDAS

In [4]:
import pandas as pd

In [6]:
#Pandas serileri Tek boyutlu bir array gibidir. 
#Numpy arrayinden farkı, değerlerin indeks bilgisiyle birlikte tutulmasıdır.
pd.Series([10,20,30,40])

0    10
1    20
2    30
3    40
dtype: int64

In [7]:
seri = pd.Series([100,56,23,67,2])

In [8]:
type(seri)

pandas.core.series.Series

In [9]:
#serinin indeks bilgilerini verir (5'e kadar):
seri.axes

[RangeIndex(start=0, stop=5, step=1)]

In [10]:
#indeks dışındaki değerlere erişmek için:
seri.values

array([100,  56,  23,  67,   2], dtype=int64)

In [11]:
seri.index

RangeIndex(start=0, stop=5, step=1)

In [12]:
#ilk 5 veriyi getirir. 3 yazarsak 3 değeri getirir.
seri.head(3)

0    100
1     56
2     23
dtype: int64

In [13]:
seri.head()

0    100
1     56
2     23
3     67
4      2
dtype: int64

In [14]:
#Sondan elemana erişmek
seri.tail(3)

2    23
3    67
4     2
dtype: int64

index isimlendirmesi

In [15]:
pd.Series([1,2,3,4,5,6])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [16]:
#indeks isimlendirmesi için:
pd.Series([1,2,3,4,5,6], index = [1,3,5,7,9,10])

1     1
3     2
5     3
7     4
9     5
10    6
dtype: int64

In [22]:
seri=pd.Series([10,20,30,40],index=["a","b","c","d"])

In [20]:
seri.values

array([100,  56,  23,  67,   2], dtype=int64)

In [23]:
seri.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [24]:
#index ismi ile elemana erişme
seri["a"]

10

In [25]:
seri["a":"c"]

a    10
b    20
c    30
dtype: int64

Eleman işlemleri

In [27]:
import numpy as np
a = np.array([46,23,73,32,65])
seri = pd.Series(a)
seri

0    46
1    23
2    73
3    32
4    65
dtype: int32

In [28]:
seri[0]

46

In [29]:
seri[1:4]

1    23
2    73
3    32
dtype: int32

In [32]:
seri=pd.Series([15,86,94,17],index=["satır1","satır2","satır3","satır4"])
seri

satır1    15
satır2    86
satır3    94
satır4    17
dtype: int64

In [33]:
seri.index

Index(['satır1', 'satır2', 'satır3', 'satır4'], dtype='object')

In [34]:
#Serideki değerlere erişmek için:
seri.keys

<bound method Series.keys of satır1    15
satır2    86
satır3    94
satır4    17
dtype: int64>

In [37]:
#Serideki her bir key değerine karşılık value değeri:
list(seri.items())

[('satır1', 15), ('satır2', 86), ('satır3', 94), ('satır4', 17)]

In [38]:
#eleman sorgulama
"satır1" in seri

True

In [40]:
"satır5"in seri

False

In [42]:
seri["satır2"]

86

In [43]:
#fancy eleman

In [46]:
seri[["satır2","satır4"]]

satır2    86
satır4    17
dtype: int64

In [47]:
seri["satır2"]=10 #kalıcı olarak degişir

In [48]:
seri["satır2"]

10

In [49]:
seri["satır2":"satır5"]

satır2    10
satır3    94
satır4    17
dtype: int64

pandas DataFrame oluşturma

In [50]:
#excele benzer bir yapı.Numpy fixed type olduğundan kategorik ve sürekli değişkenleri 
#bir arada tutup işlem yapak zorlaşıyor. Bu noktada Pandas daha fazla avantaja sahip.
liste = [15,23,67,33,46]

In [51]:
liste

[15, 23, 67, 33, 46]

In [52]:
pd.DataFrame(liste,columns=["sütün_ismi"])

sütün_ismi
0          15
1          23
2          67
3          33
4          46

In [57]:
m=np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
pd.DataFrame(m,columns=["sütün1","sütün2","sütün3"])

sütün1  sütün2  sütün3
0       1       2       3
1       4       5       6
2       7       8       9

In [58]:
#df isimlendirme
#dataframei bir degişkene atayıp işlem yapma:
df=pd.DataFrame(m,columns=["sutun1","sutun2","sutun3"])
df

sutun1  sutun2  sutun3
0       1       2       3
1       4       5       6
2       7       8       9

In [61]:
df.columns=("col1","col2","col3")
df

col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [62]:
#satır ve sutun bilgileri
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [63]:
df.shape

(3, 3)

In [64]:
df.ndim

2

In [65]:
df.size

9

In [66]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
df.head(2)

col1  col2  col3
0     1     2     3
1     4     5     6

In [69]:
df.tail(1)

col1  col2  col3
2     7     8     9

In [70]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [71]:
pd.DataFrame(a,columns=["col1"])

col1
0     1
1     2
2     3
3     4
4     5

eleman işlemleri

In [73]:
s1=np.random.randint(10,size=5)
s2=np.random.randint(10,size=5)
s3=np.random.randint(10,size=5)

In [74]:
sozluk={"var1":s1,"var2":s2,"var3":s3}
sozluk

{'var1': array([0, 2, 3, 8, 3]),
 'var2': array([1, 6, 1, 0, 9]),
 'var3': array([3, 2, 6, 5, 1])}

In [75]:
df=pd.DataFrame(sozluk)
df

var1  var2  var3
0     0     1     3
1     2     6     2
2     3     1     6
3     8     0     5
4     3     9     1

In [76]:
df[0:1]

var1  var2  var3
0     0     1     3

In [77]:
df[2:5]

var1  var2  var3
2     3     1     6
3     8     0     5
4     3     9     1

In [78]:
df.index=["a","b","c","d","e"]

In [79]:
df

var1  var2  var3
a     0     1     3
b     2     6     2
c     3     1     6
d     8     0     5
e     3     9     1

In [80]:
df["c":"e"]

var1  var2  var3
c     3     1     6
d     8     0     5
e     3     9     1

In [81]:
#silme
df.drop("a",axis=0)

var1  var2  var3
b     2     6     2
c     3     1     6
d     8     0     5
e     3     9     1

In [82]:
df.drop("var1",axis=1)

var2  var3
a     1     3
b     6     2
c     1     6
d     0     5
e     9     1

In [83]:
#Veri setinde değişiklik olmaz:
df

var1  var2  var3
a     0     1     3
b     2     6     2
c     3     1     6
d     8     0     5
e     3     9     1

In [85]:
#inplace işlemin kalıcı olmasını sağlar
df.drop("a",axis=0,inplace=True)

In [86]:
df

var1  var2  var3
b     2     6     2
c     3     1     6
d     8     0     5
e     3     9     1

In [87]:
#fancy

In [88]:
n=["c","e"]

In [90]:
df.drop(n, axis = 0)

var1  var2  var3
b     2     6     2
d     8     0     5

In [91]:
#Sütunlar/degiskenler icin

In [92]:
df

var1  var2  var3
b     2     6     2
c     3     1     6
d     8     0     5
e     3     9     1

In [93]:
df["var4"]=df["var1"]*df["var2"]

In [94]:
df

var1  var2  var3  var4
b     2     6     2    12
c     3     1     6     3
d     8     0     5     0
e     3     9     1    27

In [95]:
df.drop("var4", axis = 1)

var1  var2  var3
b     2     6     2
c     3     1     6
d     8     0     5
e     3     9     1

In [98]:
df.drop("var3",axis=1,inplace=True)

In [99]:
df

var1  var2  var4
b     2     6    12
c     3     1     3
d     8     0     0
e     3     9    27

gözlem ve değişken seçimi:loc&iloc

In [1]:
import numpy as np
import pandas as pd

In [6]:
m=np.random.randint(1,30,size=(10,3))
m
df=pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0    16     7    25
1     7    16    16
2    26    16    16
3     3    23    28
4     2    23     6
5     1     2    13
6    17     7    20
7    20    10    26
8    11    10    16
9    16    22    22

In [8]:
#loc: tanımlandığı şekli ile seçim yapmak için kullanılır.
df.loc[0:3]#3'ü de dahil eder.

var1  var2  var3
0    16     7    25
1     7    16    16
2    26    16    16
3     3    23    28

In [9]:
#iloc: alışık olduğumuz indeksleme mantığı ile seçim yapar. 3'ü dahil etmez:
df.iloc[0:3]

var1  var2  var3
0    16     7    25
1     7    16    16
2    26    16    16

In [10]:
df

var1  var2  var3
0    16     7    25
1     7    16    16
2    26    16    16
3     3    23    28
4     2    23     6
5     1     2    13
6    17     7    20
7    20    10    26
8    11    10    16
9    16    22    22

In [12]:
df.iloc[2,0]

26

In [15]:
df

var1  var2  var3
0    16     7    25
1     7    16    16
2    26    16    16
3     3    23    28
4     2    23     6
5     1     2    13
6    17     7    20
7    20    10    26
8    11    10    16
9    16    22    22

In [16]:
df.iloc[:2,:3]

var1  var2  var3
0    16     7    25
1     7    16    16

In [17]:
df.loc[0:3, "var3"]

0    25
1    16
2    16
3    28
Name: var3, dtype: int32

In [18]:
df.iloc[0:4]["var3"]

0    25
1    16
2    16
3    28
Name: var3, dtype: int32

koşullu eleman işlemleri

In [19]:
#gözlem aralığı seçme:
df[0:2][["var1","var2"]]

var1  var2
0    16     7
1     7    16

In [20]:
df.var1

0    16
1     7
2    26
3     3
4     2
5     1
6    17
7    20
8    11
9    16
Name: var1, dtype: int32

In [21]:
df[df.var1>15]

var1  var2  var3
0    16     7    25
2    26    16    16
6    17     7    20
7    20    10    26
9    16    22    22

In [24]:
df[(df.var1 < 5) & (df.var3 < 15)]

var1  var2  var3
4     2    23     6
5     1     2    13

In [25]:
df

var1  var2  var3
0    16     7    25
1     7    16    16
2    26    16    16
3     3    23    28
4     2    23     6
5     1     2    13
6    17     7    20
7    20    10    26
8    11    10    16
9    16    22    22

In [27]:
df.loc[(df.var1>15)][["var1","var2"]]

var1  var2
0    16     7
2    26    16
6    17     7
7    20    10
9    16    22

birleştirme join işlemleri

In [28]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1","var2","var3"])
df1

var1  var2  var3
0    14    29    27
1    20    21     7
2    10    15     4
3     1     2    22
4     1     4    11

In [29]:
df2=df1+99

In [30]:
df2

var1  var2  var3
0   113   128   126
1   119   120   106
2   109   114   103
3   100   101   121
4   100   103   110

In [31]:
pd.concat([df1,df2])#birleştiriyor
#indeksler bozuldu:

var1  var2  var3
0    14    29    27
1    20    21     7
2    10    15     4
3     1     2    22
4     1     4    11
0   113   128   126
1   119   120   106
2   109   114   103
3   100   101   121
4   100   103   110

In [32]:
pd.concat([df1,df2], ignore_index=True)

var1  var2  var3
0    14    29    27
1    20    21     7
2    10    15     4
3     1     2    22
4     1     4    11
5   113   128   126
6   119   120   106
7   109   114   103
8   100   101   121
9   100   103   110

In [33]:
df2.columns=["var1","var2","deg3"]
df2

var1  var2  deg3
0   113   128   126
1   119   120   106
2   109   114   103
3   100   101   121
4   100   103   110

In [34]:
df1

var1  var2  var3
0    14    29    27
1    20    21     7
2    10    15     4
3     1     2    22
4     1     4    11

In [35]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0    14    29  27.0    NaN
1    20    21   7.0    NaN
2    10    15   4.0    NaN
3     1     2  22.0    NaN
4     1     4  11.0    NaN
0   113   128   NaN  126.0
1   119   120   NaN  106.0
2   109   114   NaN  103.0
3   100   101   NaN  121.0
4   100   103   NaN  110.0

In [36]:
#kesişimlerine göre birleştirme:
pd.concat([df1, df2], join = "inner")

var1  var2
0    14    29
1    20    21
2    10    15
3     1     2
4     1     4
0   113   128
1   119   120
2   109   114
3   100   101
4   100   103

ileri birleştirme işlemleri

In [38]:
df1 = pd.DataFrame({'calisanlar': ['nesli', 'irem', 'melisa'],
                    'meslek': ['muhendislik', 'Muhendislik', 'edebiyat']})
df1

calisanlar       meslek
0      nesli  muhendislik
1       irem  Muhendislik
2     melisa     edebiyat

In [40]:
df2 = pd.DataFrame({'calisanlar': ['nesli', 'irem', 'melisa'],
                    'ilk_giris': [2021, 2021, 2020]})
df2

calisanlar  ilk_giris
0      nesli       2021
1       irem       2021
2     melisa       2020

In [41]:
#Tüm elemanların 2 veri setinde de aynen alma durumunda birleştirme:
pd.merge(df1, df2)

calisanlar       meslek  ilk_giris
0      nesli  muhendislik       2021
1       irem  Muhendislik       2021
2     melisa     edebiyat       2020

In [42]:
#Hangi değişkene göre birleştirmenin yapılacağı belirtilmek istenirse:
pd.merge(df1, df2, on = "calisanlar")

calisanlar       meslek  ilk_giris
0      nesli  muhendislik       2021
1       irem  Muhendislik       2021
2     melisa     edebiyat       2020

Toplulaştırma ve Gruplama (Aggregation & Grouping)

Basit toplulaştırma fonksiyonları:

count()
mean()
median()
min()
max()
std()
var()
sum()

In [43]:
#veri setlerini kullanmak için:
import seaborn as sns

In [44]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [46]:
df.shape
#1035 gözlem, 6 değişken

(1035, 6)

In [47]:
df.mean()

C:\Users\Neslihan\AppData\Local\Temp\ipykernel_29304\3698961737.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.mean()


number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [48]:
#ortalama
df["mass"].mean()

2.6381605847953233

In [49]:
#değer saydırma
df["mass"].count()

513

In [50]:
df["mass"].min()

0.0036

In [51]:
df["mass"].max()

25.0

In [52]:
df["mass"].std()

3.8186166509616046

In [53]:
df["mass"].var()

14.58183312700122

In [54]:
df["mass"].sum()

1353.37638

In [55]:
#tüm betimsel istatistikler için:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [56]:
#Eksik verileri atıp inceleme:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

gruplama işlemleri

In [59]:
df=pd.DataFrame({'gruplar':['A','B','C','A','B','C'],
                'veri':[10,11,52,23,43,55]},columns=['gruplar', 'veri'])
df

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [60]:
df.groupby("gruplar")

In [62]:
df.groupby("gruplar").mean()#ort

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [63]:
df.groupby("gruplar").sum()#toplam

veri
gruplar      
A          33
B          54
C         107

In [64]:
df = sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [65]:
df.groupby("method")

In [66]:
df.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [67]:
df.groupby("method")["orbital_period"].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

pivot tablolar

In [69]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [70]:
#pivot ile table
titanic.pivot_table("survived", index = "sex", columns = "class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [72]:
titanic.age.head(15)

0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
5      NaN
6     54.0
7      2.0
8     27.0
9     14.0
10     4.0
11    58.0
12    20.0
13    39.0
14    14.0
Name: age, dtype: float64

dış kaynaklı veri okumak

In [73]:
import pandas as pd

In [74]:
?pd.read_csv

In [ ]:
#csv okuma
pd.read_csv("reading_data/ornekcsv.csv", sep = ";")

In [ ]:
#txt okuma
pd.read_csv("reading_data/duz_metin.txt")

In [ ]:
#excel
pd.read_excel("reading_data/ornekx.xlsx")

In [ ]:
df = pd.read_excel("reading_data/ornekx.xlsx")

In [76]:
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [ ]:
df.columns = ("A","B","C")
df