In [1]:
import numpy as np

In [2]:
data=np.random.rand(5)*100

In [3]:
data

array([51.0171327 , 82.26123406, 66.78937802,  2.80432758, 57.85105292])

In [4]:
def MinMaxNormalizasyonu(data):
    minVeri=np.min(data)
    maxVeri=np.max(data)
    sonuc=(data-minVeri)/(maxVeri-minVeri)
    return sonuc
# verileri 0-1 arasina normalize eder

In [9]:
normalizeEdilmisData=MinMaxNormalizasyonu(data)
print("Normalizasyon oncesi:",data)
print("********************************************************************************")
print("Normalizasyon sonrasi:",normalizeEdilmisData)

Normalizasyon oncesi: [51.0171327  82.26123406 66.78937802  2.80432758 57.85105292]
********************************************************************************
Normalizasyon sonrasi: [0.60677929 1.         0.80527991 0.         0.69278717]


In [10]:
def IstatikselNormalizasyon(data):
    ortalama=np.min(data)
    standartSapma=np.std(data)
    sonuc=(data-ortalama)/(standartSapma)
    return sonuc


In [11]:
normalizeEdilmisData2=IstatikselNormalizasyon(data)
print("Normalizasyon oncesi:",data)
print("********************************************************************************")
print("Normalizasyon sonrasi:",normalizeEdilmisData2)

Normalizasyon oncesi: [51.0171327  82.26123406 66.78937802  2.80432758 57.85105292]
********************************************************************************
Normalizasyon sonrasi: [1.79934143 2.96539692 2.38797456 0.         2.05438894]


In [12]:
def logaritmikNormalizasyon(data):
    return np.log(data)

In [13]:
normalizeEdilmisData3=logaritmikNormalizasyon(data)
print("Normalizasyon oncesi:",data)
print("********************************************************************************")
print("Normalizasyon sonrasi:",normalizeEdilmisData3)

Normalizasyon oncesi: [51.0171327  82.26123406 66.78937802  2.80432758 57.85105292]
********************************************************************************
Normalizasyon sonrasi: [3.93216151 4.40989996 4.20154406 1.03116379 4.05787165]


In [15]:
def karekokNormalizasyonu(data):
    return np.sqrt(data)

In [16]:
normalizeEdilmisData4=karekokNormalizasyonu(data)
print("Normalizasyon oncesi:",data)
print("********************************************************************************")
print("Normalizasyon sonrasi:",normalizeEdilmisData4)

Normalizasyon oncesi: [51.0171327  82.26123406 66.78937802  2.80432758 57.85105292]
********************************************************************************
Normalizasyon sonrasi: [7.14262786 9.06979791 8.17247686 1.67461267 7.60598797]


In [19]:
from sklearn.preprocessing import StandardScaler

In [21]:
data=data.reshape(-1,1)

In [22]:
sc=StandardScaler()

In [23]:
print(sc.fit(data)) # fit egit demek

StandardScaler()


In [24]:
data

array([[51.0171327 ],
       [82.26123406],
       [66.78937802],
       [ 2.80432758],
       [57.85105292]])

In [27]:
scNormalizasyon=sc.transform(data) # transform uygula demek
scNormalizasyon

array([[-0.04207894],
       [ 1.12397655],
       [ 0.54655419],
       [-1.84142037],
       [ 0.21296857]])

In [30]:
# Veri Setinde Normalizasyon 

In [31]:
import pandas as pd

In [32]:
iris=pd.read_csv("iris.csv")
iris.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [33]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
iris.variety=le.fit_transform(iris.variety)
iris.head()

sepal.length  sepal.width  petal.length  petal.width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [35]:
iris.variety.unique()

array([0, 1, 2])

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data2=scaler.fit_transform(iris)
data2

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00, -1.22474487e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00, -1.22474487e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00, -1.22474487e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00

In [37]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data=iris.values[:,:]
data=scaler.fit_transform(data)
data2=pd.DataFrame(data)
data2.head(25)

0         1         2         3         4
0  -0.900681  1.019004 -1.340227 -1.315444 -1.224745
1  -1.143017 -0.131979 -1.340227 -1.315444 -1.224745
2  -1.385353  0.328414 -1.397064 -1.315444 -1.224745
3  -1.506521  0.098217 -1.283389 -1.315444 -1.224745
4  -1.021849  1.249201 -1.340227 -1.315444 -1.224745
5  -0.537178  1.939791 -1.169714 -1.052180 -1.224745
6  -1.506521  0.788808 -1.340227 -1.183812 -1.224745
7  -1.021849  0.788808 -1.283389 -1.315444 -1.224745
8  -1.748856 -0.362176 -1.340227 -1.315444 -1.224745
9  -1.143017  0.098217 -1.283389 -1.447076 -1.224745
10 -0.537178  1.479398 -1.283389 -1.315444 -1.224745
11 -1.264185  0.788808 -1.226552 -1.315444 -1.224745
12 -1.264185 -0.131979 -1.340227 -1.447076 -1.224745
13 -1.870024 -0.131979 -1.510739 -1.447076 -1.224745
14 -0.052506  2.169988 -1.453901 -1.315444 -1.224745
15 -0.173674  3.090775 -1.283389 -1.052180 -1.224745
16 -0.537178  1.939791 -1.397064 -1.052180 -1.224745
17 -0.900681  1.019004 -1.340227 -1.183812 -1.224745
18 -0.173674  1.709595 -1.169714 -1.183812 -1.224745
19 -0.900681  1.709595 -1.283389 -1.183812 -1.224745
20 -0.537178  0.788808 -1.169714 -1.315444 -1.224745
21 -0.900681  1.479398 -1.283389 -1.052180 -1.224745
22 -1.506521  1.249201 -1.567576 -1.315444 -1.224745
23 -0.900681  0.558611 -1.169714 -0.920548 -1.224745
24 -1.264185  0.788808 -1.056039 -1.315444 -1.224745